### ISSUE TITLE
Add Support For Inventories REST calls

### ISSUE THREAD

**Issue by ryankazokas** [ChannelApe/channelape-typescript-sdk#44]
Add new calls to support the new inventories endpoints:
https://docs.channelape.io/?version=latest#ebdff427-2970-473d-9425-b997ef450fc9

The new functionality should include support for the following methods:

- POST /inventories
- PUT /inventories/{inventoryItemId}
- GET /inventories?businessId={businessId}
- GET /inventories/{inventoryItemId}

**Comment by rjdavis3** [comment]
Added as part of [1.18.0](https://github.com/ChannelApe/channelape-typescript-sdk/releases/tag/1.18.0) release.
