### ISSUE TITLE
Add support for locations REST calls

### ISSUE THREAD

**Issue by ryankazokas** [ChannelApe/channelape-typescript-sdk#45]
Add new calls to support the new locations endpoints:
https://docs.channelape.io/?version=latest#47d0bc9b-dcf0-429b-a310-45813abaec90

The new functionality should include support for the following methods:

- POST /locations
- PUT /locations/{locationId}
- GET /locations?businessId={businessId}
- GET /locations/{locationId}

**Comment by rjdavis3** [comment]
Added as part of [1.18.0](https://github.com/ChannelApe/channelape-typescript-sdk/releases/tag/1.18.0) release.
