### ISSUE TITLE
Add support for inventory quantity REST calls

### ISSUE THREAD

**Issue by ryankazokas** [ChannelApe/channelape-typescript-sdk#46]
Add new calls to support the new adjustment and quantity retrieval endpoints:
https://docs.channelape.io/?version=latest#2312dd36-bac9-4dbc-93c8-2a59edd57c49

The new functionality should include support for the following methods:

- POST /inventories/{inventoryItemId}/quantities/adjusts (adjust quantity API)
- POST /inventories/{inventoryItemId}/quantities/sets (set quantity API)
- GET /inventories/{inventoryItemId}/quantities

**Comment by rjdavis3** [comment]
Handled as part of [1.19.0](https://github.com/ChannelApe/channelape-typescript-sdk/tree/1.19.0) release.
