### ISSUE TITLE
LineItem giftCardCode should be editable

### ISSUE THREAD

**Issue by mb-ca** [ChannelApe/channelape-typescript-sdk#67]
The LineItem.giftCardCode field is currently readonly, but should be editable.

When creating fulfillments, we currently have to use `// @ts-ignore` to ignore the typescript error.

**Comment by ryankazokas** [comment]
@mb-ca i'm not sure the reason behind the readonly property for the option here, but just so you know how it works, the API does not return full gift card values on GETs/PUTs/POSTs, so doing a PUT with the value returned will wipe the code with the value passed in on the PUT.
https://www.channelape.com/support/knowledgebase/channelape-order/

**Comment by mb-ca** [comment]
@ryankazokas Thanks, this is good to note.
