### ISSUE TITLE
Ensure master branch is the only branch pushing deploying to latest tag

### ISSUE THREAD

**Issue by rjdavis3** [ChannelApe/channelape-typescript-sdk#82]
When we were using Tracis CI we maintained a latest tag and a develop tag. `latest` tag was always stable while `develop` had new features in the works. GitFlow is always publishing to latest no matter what branch we are publishing from.

![image](https://user-images.githubusercontent.com/2506662/132426547-dd50226b-4e4c-4ec3-8116-b95f6b27fb7d.png)

It looks like GitHub Actions [support tags](https://github.com/marketplace/actions/npm-publish) so we should try to implement this so new pushes of master go to `latest` and new pushes off of develop branch go to `develop` tag.

Here is how it was working with Travis for reference:
https://github.com/ChannelApe/channelape-typescript-sdk/blob/1.28.1/.travis.yml#L30

**Comment by rjdavis3** [comment]
@mb-ca thanks for setting up GitHub Actions for us. Here is one improvement I think we will need to ensure the `latest` tag remains stable while we test new features.

**Comment by mb-ca** [comment]
Resolved with 1.30.0.  Thanks for pointing this out @rjdavis3.
